version: '2'

services:
    mysql:
        image: mysql
        volumes:
            - "./docker/data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test
    php:
        build: docker/php7-fpm
        ports:
            - 9000:9000
        links:
            - mysql:mysql
        volumes:
            - ./:/var/www/test
    nginx:
        build: docker/nginx
        ports:
            - 80:80
        links:
            - php
        volumes_from:
            - php
