<?php

namespace SudokuBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * GrilleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrilleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllWinCommand($key)
    {
        return $this->_em->createQuery("UPDATE SudokuBundle:Grille s SET s.resolved2 = 'Win' WHERE s.id = '$key'")
            ->getResult();
    }

    public function getAllWinButton($key)
    {
        return $this->_em->createQuery("UPDATE SudokuBundle:Grille s SET s.resolved = 'Win' WHERE s.id = '$key'")
            ->getResult();
    }

    public function findButtonWinner()
    {
        return $this->_em->createQuery("SELECT s FROM SudokuBundle:Grille s WHERE s.resolved = 'Win'")
            ->setMaxResults(3)
            ->getResult();
    }

    public function findCommandWinner()
    {
        return $this->_em->createQuery("SELECT s FROM SudokuBundle:Grille s WHERE s.resolved2 = 'Win'")
            ->setMaxResults(3)
            ->getResult();
    }
}
