<?php

namespace SudokuBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping as ORM;
/**
 * GrilleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrilleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllWin($key){
        return $this->_em->createQuery("UPDATE SudokuBundle:Grille s SET s.resolved = 'Win' WHERE s.id = '$key'")
            ->getResult();
    }
}
