sudoku:
    resource: "@SudokuBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fjdsudoku:
    resource: "@SudokuBundle/Controller/DefaultController.php"
    type:     annotation
    prefix: /